# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-13 01:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='手机号')),
                ('addr', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('id_code', models.CharField(blank=True, max_length=30, verbose_name='身份证号码')),
                ('gender', models.IntegerField(blank=True, choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('nickname', models.CharField(blank=True, max_length=200, verbose_name='昵称')),
                ('head', models.CharField(blank=True, max_length=300, verbose_name='头像')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
