# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 15:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersystem', '0002_remove_userinfo_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='invite_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublevel', to=settings.AUTH_USER_MODEL, verbose_name='邀请人'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='invite_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='邀请码'),
        ),
    ]
