# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-27 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhanRich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_label', models.CharField(blank=True, max_length=30, verbose_name='菜单显示名')),
                ('label', models.CharField(blank=True, max_length=30, verbose_name='大显示名')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='图片')),
                ('content', models.TextField(blank=True, verbose_name='主要内容')),
                ('page', models.CharField(blank=True, choices=[('zhanshi', '区域展示'), ('xuanchuan', '品牌宣传')], max_length=30, verbose_name='从属页面')),
            ],
        ),
    ]
