# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-29 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanrich',
            name='priority',
            field=models.IntegerField(default=0, help_text='大的排列在前', verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='zhanrich',
            name='label',
            field=models.CharField(blank=True, help_text='显示位置，请参看demo页面', max_length=30, verbose_name='大显示名'),
        ),
    ]
