# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_auto_20180929_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='显示名')),
                ('order', models.IntegerField(default=0, help_text='排序，越小越前面', verbose_name='顺序')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='显示名')),
                ('status', models.CharField(choices=[('un_avaliable', '不可用'), ('sold', '已售'), ('avaliable', '可用')], default='un_avaliable', max_length=30, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_2d', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='2D图片')),
                ('img_3d', models.CharField(blank=True, max_length=300, verbose_name='3D链接')),
            ],
        ),
        migrations.AddField(
            model_name='floor',
            name='floortype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.FloorType', verbose_name='户型'),
        ),
    ]
