# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_auto_20181005_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='order',
            field=models.IntegerField(default=0, help_text='排序，越小越前面', verbose_name='顺序'),
        ),
        migrations.AddField(
            model_name='floortype',
            name='label',
            field=models.CharField(default='', max_length=30, verbose_name='户型名'),
            preserve_default=False,
        ),
    ]
