# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0004_auto_20181005_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpage.Building', verbose_name='栋'),
        ),
    ]
