# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-18 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_floor_build'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhanrich',
            name='page',
            field=models.CharField(blank=True, choices=[('zhanshi', '区域展示'), ('xuanchuan', '品牌宣传'), ('manual', '项目手册')], max_length=30, verbose_name='从属页面'),
        ),
    ]
