# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_auto_20181118_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='显示名')),
                ('pos', models.CharField(max_length=30, verbose_name='坐标')),
                ('icon', helpers.director.model_func.cus_fields.cus_picture.PictureField(max_length=200, verbose_name='图标')),
                ('url', models.CharField(max_length=200, verbose_name='跳转地址')),
            ],
        ),
    ]
