# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0007_mappoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='label_pos',
            field=models.CharField(default='', help_text='请严格按照 x,y 的格式填写', max_length=30, verbose_name='标签坐标'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='pos',
            field=models.CharField(help_text='请严格按照 x,y 的格式填写', max_length=30, verbose_name='坐标'),
        ),
    ]
