# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_auto_20181201_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名')),
                ('pos', models.CharField(help_text='请严格按照 x,y 的格式填写', max_length=30, verbose_name='坐标')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名')),
                ('area', models.ManyToManyField(to='webpage.Area', verbose_name='区域')),
                ('project', models.ManyToManyField(to='webpage.MapPoint', verbose_name='项目点')),
            ],
        ),
    ]
