# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-01 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_auto_20181201_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='width',
            field=models.IntegerField(default=100, help_text='区域图片宽度，用于地图定位', verbose_name='宽度'),
            preserve_default=False,
        ),
    ]
