# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_area_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='bg_pic',
            field=helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='区域图'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='bg_pos',
            field=models.CharField(blank=True, help_text='请严格按照 x,y 的格式填写', max_length=30, verbose_name='背景坐标'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='bg_width',
            field=models.IntegerField(default=100, help_text='区域图片宽度，用于地图定位', verbose_name='宽度'),
        ),
    ]
