# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-08 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_auto_20181205_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='显示名')),
                ('pos', models.CharField(help_text='请严格按照 x,y 的格式填写', max_length=30, verbose_name='坐标')),
                ('pic', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=300, verbose_name='区域图')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='width',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='bg_pic',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='bg_pos',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='bg_width',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='mappoint',
            name='label_pos',
        ),
        migrations.AddField(
            model_name='mainpageitem',
            name='img_list',
            field=models.ManyToManyField(blank=True, to='webpage.PageImages', verbose_name='区域'),
        ),
    ]
