# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-21 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20181208_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimages',
            name='link',
            field=models.CharField(blank=True, max_length=300, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='mainpageitem',
            name='img_list',
            field=models.ManyToManyField(blank=True, to='webpage.PageImages', verbose_name='图片列表'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='url',
            field=models.CharField(blank=True, max_length=200, verbose_name='3D资源地址'),
        ),
    ]
