# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0014_auto_20181221_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='direct_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='直接连接地址'),
        ),
    ]
